Import from @remix-run/node
sergiodxa/remix-auth pull request #150
Opened 2022-03-29 11:19 UTC by machour

See comment here: https://github.com/remix-run/remix/issues/2503#issuecomment-1079963155

2022-03-29 14:18 UTC, MichaelDeBoey requested changes
It's still possible to get these imports from `remix` package, but once the codemod is ready it will be recommended to update all imports, so good to already do it here. 👍

This means we'll need to have at least v1.3.3 as a dependency though, as `createCookieSessionStorage` wasn't exported from `@remix-run/node` before that.

2022-04-06 22:59 UTC, sergiodxa approved these changes

2022-04-06 22:59 UTC, merged

2022-04-07 02:08 UTC, MichaelDeBoey commented
@sergiodxa as stated above, this would be a breaking change to not use `remix` package internally as this resuires updated `peerDependencies`

2022-04-07 05:28 UTC, sergiodxa commented
> @sergiodxa as stated above, this would be a breaking change to not use `remix` package internally as this resuires updated `peerDependencies`

This only change docs and a test file, or direct change anything of how Remix Auth works.